const sketch = require('./challenges/sketch')
const narcNumber = require('./challenges/narcNumber')
const strEndsWith = require ('./challenges/strEndsWith')
const uniqueInOrder = require ('./challenges/uniqueInOrder')
const highAndLow = require('./challenges/highAndLow')
const dnaStrand = require('./challenges/dnaStrand')
const toCamelCase = require('./challenges/toCamelCase')
const persistence = require('./challenges/anagrams')
const romanNumerals = require('./challenges/romanNumerals')
const anagrams = require('./challenges/anagrams')
const countBits = require('./challenges/countBits')
const stringToBinary = require('./challenges/stringToBinary')
const iqTest = require('./challenges/iqTest')


// console.log(sketch())
// console.log(narcNumber(153))
// console.log(strEndsWith('wallace', 'ace'))
// console.log(uniqueInOrder('AAAABBBCCDAABBB'))
// console.log(highAndLow("4 5 29 54 4 0 -214 542 -64 1 -3 6 -6"))
// console.log(dnaStrand('ATTGC'))
// console.log(toCamelCase('snake_case_any'))
// console.log(persistence(123))
// console.log(romanNumerals(2020))
// console.log(anagrams('dcba', ['abdc', 'adbc', 'bcda']))
// console.log(countBits(8))
// console.log(stringToBinary('Caren')) 
// console.log(iqTest('2 3 4 6 8 10'))
