const sketch = require('./challenges/sketch')
const strEndsWith = require ('./challenges/strEndsWith')
const uniqueInOrder = require ('./challenges/uniqueInOrder')
const highAndLow = require('./challenges/highAndLow')
const dnaStrand = require('./challenges/dnaStrand')
const toCamelCase = require('./challenges/toCamelCase')
const persistence = require('./challenges/persistence')


// console.log(sketch())
// console.log(strEndsWith('wallace', 'ace'))
// console.log(uniqueInOrder('AAAABBBCCDAABBB'))
// console.log(highAndLow("4 5 29 54 4 0 -214 542 -64 1 -3 6 -6"))
// console.log(dnaStrand('ATTGC'))
// console.log(toCamelCase('snake_case_any'))
console.log(persistence(123))